### ISSUE TITLE
Weird dependencies?

### ISSUE THREAD

**Issue by tunnckoCore** [doctorfree/Asciiville#11]
Hey, cool package, but i'm seeing weird dependencies on Arch Linux AUR..

![image](https://github.com/doctorfree/Asciiville/assets/5038030/2c6f9fe7-86aa-421a-92f6-41b882bff9c4)

![image](https://github.com/doctorfree/Asciiville/assets/5038030/d8cebe2c-78b3-4383-9fda-9219cb42cb81)

What neomutt, newsboat, mplayer, ranger, w3m, and neofetch has to do with all that at all?

**Comment by doctorfree** [comment]
Asciiville is a suite of character based utilities as well as an Ascii Art studio.
